# Generated by Django 5.1.5 on 2026-02-25 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_userflashcard_title'),
        ('rag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userflashcard',
            name='card_type',
            field=models.CharField(choices=[('standard', 'Padrão'), ('cloze', 'Cloze Deletion'), ('reverse', 'Inversão P/R'), ('mcq', 'Múltipla Escolha')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Coleção/matéria associada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='rag.collection'),
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='is_corrective',
            field=models.BooleanField(default=False, help_text='Flashcard gerado automaticamente após erro em revisão'),
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Documento de origem (se gerado via RAG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='rag.document'),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Auto-avaliação de confiança (0-5)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='flashcards.userflashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(help_text='Explicação gerada pela IA com base nos documentos do usuário')),
                ('source_chunks', models.JSONField(default=list, help_text='Lista de chunks usados como fonte: [{chunk_id, document_title, excerpt}]')),
                ('corrective_flashcards', models.JSONField(blank=True, default=list, help_text='Flashcards corretivos sugeridos: [{title, content, card_type}]')),
                ('model_used', models.CharField(default='gpt-4-turbo', max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='flashcards.reviewlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
